name = "caja-frontend"
type = "javascript"
compatibility_date = "2026-04-22"

[build]
command = "./build.sh"
cwd = "./"
watch_paths = ["frontend/**/*.{ts,tsx,astro}"]

[env.production]
name = "caja-frontend"
